### ISSUE TITLE
Not enough cake

### ISSUE THREAD

**Issue by wiedenm** [kickuth/osm-route-finder#1]
There is not enough cake in https://github.com/kickuth/osm-route-finder/blob/f04c5d03fc5a0451fdefa3e910dd1fb885e766eb/osm-maxsequence/src/main/resources/web/map.vm#L48

I'd suggest to change the relevant line to `<a href="https://www.google.com/search?q=more%20cake">More cake?</a>`.

**Comment by kickuth** [comment]
For now, we are all out of cake. We might get some more in the future.
